CREATE TABLE betalens.entity_dim (
    entity_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(32) NOT NULL UNIQUE,
    entity_type VARCHAR(16) NOT NULL DEFAULT 'unknown'
        CHECK (entity_type IN ('stock', 'index', 'fund', 'bond', 'macro', 'unknown')),
    current_name VARCHAR(200) NOT NULL DEFAULT '',
    first_trade_date DATE,
    delist_date DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    CHECK (delist_date IS NULL OR first_trade_date IS NULL OR delist_date >= first_trade_date)
);
CREATE INDEX idx_entity_dim_type_code ON betalens.entity_dim (entity_type, code);

CREATE TABLE betalens.entity_name_history (
    entity_id BIGINT NOT NULL REFERENCES betalens.entity_dim(entity_id) ON DELETE CASCADE,
    valid_from TIMESTAMP NOT NULL,
    valid_to TIMESTAMP,
    name VARCHAR(200) NOT NULL,
    PRIMARY KEY (entity_id, valid_from),
    CHECK (valid_to IS NULL OR valid_to > valid_from)
);
CREATE INDEX idx_entity_name_history_asof
    ON betalens.entity_name_history (entity_id, valid_from DESC, valid_to);

CREATE TABLE betalens.metric_dim (
    metric_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    logical_dataset VARCHAR(32) NOT NULL,
    metric_name VARCHAR(160) NOT NULL,
    storage_kind VARCHAR(16) NOT NULL DEFAULT 'observation'
        CHECK (storage_kind IN ('core', 'observation')),
    storage_column VARCHAR(32),
    availability_time TIME NOT NULL DEFAULT TIME '15:00:01',
    unit VARCHAR(32),
    description TEXT,
    CONSTRAINT uq_metric_dim_dataset_name UNIQUE (logical_dataset, metric_name),
    CONSTRAINT uq_metric_dim_id_dataset UNIQUE (metric_id, logical_dataset),
    CHECK (
        (storage_kind = 'core' AND storage_column IN
            ('open', 'high', 'low', 'close', 'prev_close', 'volume', 'amount', 'turnover_rate'))
        OR (storage_kind = 'observation' AND storage_column IS NULL)
    )
);
CREATE INDEX idx_metric_dim_storage
    ON betalens.metric_dim (logical_dataset, storage_kind, storage_column);

CREATE TABLE betalens.metric_alias (
    logical_dataset VARCHAR(32) NOT NULL,
    alias VARCHAR(160) NOT NULL,
    metric_id INTEGER NOT NULL,
    PRIMARY KEY (logical_dataset, alias),
    CONSTRAINT fk_metric_alias_metric_dataset
        FOREIGN KEY (metric_id, logical_dataset)
        REFERENCES betalens.metric_dim(metric_id, logical_dataset)
        ON DELETE CASCADE
);
CREATE INDEX idx_metric_alias_metric ON betalens.metric_alias (metric_id);

INSERT INTO betalens.metric_dim
    (logical_dataset, metric_name, storage_kind, storage_column, availability_time, unit)
VALUES
    ('daily_market', '开盘价(元)', 'core', 'open', TIME '09:30:01', '元'),
    ('daily_market', '最高价(元)', 'core', 'high', TIME '15:00:01', '元'),
    ('daily_market', '最低价(元)', 'core', 'low', TIME '15:00:01', '元'),
    ('daily_market', '收盘价(元)', 'core', 'close', TIME '15:00:01', '元'),
    ('daily_market', '前收盘价', 'core', 'prev_close', TIME '09:30:01', '元'),
    ('daily_market', '成交量(股)', 'core', 'volume', TIME '15:00:01', '股'),
    ('daily_market', '成交金额(元)', 'core', 'amount', TIME '15:00:01', '元'),
    ('daily_market', '换手率(%)', 'core', 'turnover_rate', TIME '15:00:01', '%'),
    ('daily_index', '开盘价', 'core', 'open', TIME '09:30:01', NULL),
    ('daily_index', '最高价', 'core', 'high', TIME '15:00:01', NULL),
    ('daily_index', '最低价', 'core', 'low', TIME '15:00:01', NULL),
    ('daily_index', '收盘价', 'core', 'close', TIME '15:00:01', NULL),
    ('daily_index', '前收盘价', 'core', 'prev_close', TIME '09:30:01', NULL),
    ('daily_index', '成交量', 'core', 'volume', TIME '15:00:01', NULL),
    ('daily_index', '成交额', 'core', 'amount', TIME '15:00:01', NULL),
    ('daily_index', '换手率', 'core', 'turnover_rate', TIME '15:00:01', '%'),
    ('daily_fund', '开盘价(元)', 'core', 'open', TIME '09:30:01', '元'),
    ('daily_fund', '最高价(元)', 'core', 'high', TIME '15:00:01', '元'),
    ('daily_fund', '最低价(元)', 'core', 'low', TIME '15:00:01', '元'),
    ('daily_fund', '收盘价(元)', 'core', 'close', TIME '15:00:01', '元'),
    ('daily_fund', '前收盘价', 'core', 'prev_close', TIME '09:30:01', '元'),
    ('daily_fund', '成交量(份)', 'core', 'volume', TIME '15:00:01', '份'),
    ('daily_fund', '成交额(元)', 'core', 'amount', TIME '15:00:01', '元'),
    ('daily_fund', '换手率(%)', 'core', 'turnover_rate', TIME '15:00:01', '%'),
    ('daily_bond', '开盘价(元)', 'core', 'open', TIME '09:30:01', '元'),
    ('daily_bond', '最高价(元)', 'core', 'high', TIME '15:00:01', '元'),
    ('daily_bond', '最低价(元)', 'core', 'low', TIME '15:00:01', '元'),
    ('daily_bond', '收盘价(元)', 'core', 'close', TIME '15:00:01', '元'),
    ('daily_bond', '前收盘价', 'core', 'prev_close', TIME '09:30:01', '元'),
    ('daily_bond', '成交量(手)', 'core', 'volume', TIME '15:00:01', '手'),
    ('daily_bond', '成交额(元)', 'core', 'amount', TIME '15:00:01', '元'),
    ('daily_bond', '换手率(%)', 'core', 'turnover_rate', TIME '15:00:01', '%');

INSERT INTO betalens.metric_alias (logical_dataset, alias, metric_id)
SELECT logical_dataset, metric_name, metric_id
FROM betalens.metric_dim;

INSERT INTO betalens.metric_alias (logical_dataset, alias, metric_id)
SELECT seed.logical_dataset, seed.alias, metric.metric_id
FROM (VALUES
    ('daily_market', '开盘价', '开盘价(元)'),
    ('daily_market', '最高价', '最高价(元)'),
    ('daily_market', '最低价', '最低价(元)'),
    ('daily_market', '收盘价', '收盘价(元)'),
    ('daily_market', '前收盘价(元)', '前收盘价'),
    ('daily_market', '成交量', '成交量(股)'),
    ('daily_market', '成交额', '成交金额(元)'),
    ('daily_market', '成交额(元)', '成交金额(元)'),
    ('daily_market', '成交金额', '成交金额(元)'),
    ('daily_market', '换手率', '换手率(%)'),
    ('daily_index', '开盘价(元)', '开盘价'),
    ('daily_index', '最高价(元)', '最高价'),
    ('daily_index', '最低价(元)', '最低价'),
    ('daily_index', '收盘价(元)', '收盘价'),
    ('daily_index', '前收盘价(元)', '前收盘价'),
    ('daily_index', '成交金额(元)', '成交额'),
    ('daily_index', '成交额(元)', '成交额'),
    ('daily_index', '换手率(%)', '换手率'),
    ('daily_fund', '开盘价', '开盘价(元)'),
    ('daily_fund', '最高价', '最高价(元)'),
    ('daily_fund', '最低价', '最低价(元)'),
    ('daily_fund', '收盘价', '收盘价(元)'),
    ('daily_fund', '前收盘价(元)', '前收盘价'),
    ('daily_fund', '成交金额(元)', '成交额(元)'),
    ('daily_fund', '成交额', '成交额(元)'),
    ('daily_fund', '成交量', '成交量(份)'),
    ('daily_fund', '换手率', '换手率(%)'),
    ('daily_bond', '开盘价', '开盘价(元)'),
    ('daily_bond', '最高价', '最高价(元)'),
    ('daily_bond', '最低价', '最低价(元)'),
    ('daily_bond', '收盘价', '收盘价(元)'),
    ('daily_bond', '前收盘价(元)', '前收盘价'),
    ('daily_bond', '成交金额(元)', '成交额(元)'),
    ('daily_bond', '成交额', '成交额(元)'),
    ('daily_bond', '成交量', '成交量(手)'),
    ('daily_bond', '换手率', '换手率(%)')
) AS seed(logical_dataset, alias, canonical_name)
JOIN betalens.metric_dim metric
  ON metric.logical_dataset = seed.logical_dataset
 AND metric.metric_name = seed.canonical_name;
