CREATE TABLE betalens.industry_scheme_dim (
    scheme_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scheme_name VARCHAR(160) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE betalens.industry_dim (
    industry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scheme_id INTEGER NOT NULL REFERENCES betalens.industry_scheme_dim(scheme_id) ON DELETE RESTRICT,
    industry_code VARCHAR(64) NOT NULL,
    industry_name VARCHAR(200) NOT NULL,
    UNIQUE (scheme_id, industry_code)
);
CREATE INDEX idx_industry_dim_scheme_name
    ON betalens.industry_dim (scheme_id, industry_name);

CREATE TABLE betalens.industry_membership (
    entity_id BIGINT NOT NULL REFERENCES betalens.entity_dim(entity_id) ON DELETE CASCADE,
    industry_id BIGINT NOT NULL REFERENCES betalens.industry_dim(industry_id) ON DELETE RESTRICT,
    valid_from TIMESTAMP NOT NULL,
    valid_to TIMESTAMP,
    remark JSONB,
    PRIMARY KEY (entity_id, industry_id, valid_from),
    CHECK (valid_to IS NULL OR valid_to > valid_from)
);
CREATE INDEX idx_industry_membership_entity_asof
    ON betalens.industry_membership (entity_id, valid_from DESC, valid_to, industry_id);
CREATE INDEX idx_industry_membership_industry_asof
    ON betalens.industry_membership (industry_id, valid_from, valid_to, entity_id);

CREATE TABLE betalens.index_snapshot (
    snapshot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    index_entity_id BIGINT NOT NULL REFERENCES betalens.entity_dim(entity_id) ON DELETE CASCADE,
    effective_at TIMESTAMP NOT NULL,
    index_name_snapshot VARCHAR(200) NOT NULL DEFAULT '',
    remark JSONB,
    CONSTRAINT uq_index_snapshot_entity_effective UNIQUE (index_entity_id, effective_at)
);

CREATE TABLE betalens.index_constituent (
    snapshot_id BIGINT NOT NULL REFERENCES betalens.index_snapshot(snapshot_id) ON DELETE CASCADE,
    constituent_entity_id BIGINT NOT NULL REFERENCES betalens.entity_dim(entity_id) ON DELETE RESTRICT,
    ordinal INTEGER,
    weight DOUBLE PRECISION,
    remark JSONB,
    PRIMARY KEY (snapshot_id, constituent_entity_id),
    CHECK (ordinal IS NULL OR ordinal > 0)
);
CREATE INDEX idx_index_constituent_entity
    ON betalens.index_constituent (constituent_entity_id, snapshot_id);

CREATE TABLE betalens.trade_status_event (
    entity_id BIGINT NOT NULL REFERENCES betalens.entity_dim(entity_id) ON DELETE CASCADE,
    event_date DATE NOT NULL,
    status SMALLINT NOT NULL CHECK (status IN (-1, 0, 1)),
    status_text VARCHAR(100) NOT NULL DEFAULT '',
    remark JSONB,
    PRIMARY KEY (entity_id, event_date)
);
CREATE INDEX idx_trade_status_event_date_entity
    ON betalens.trade_status_event (event_date, entity_id);

CREATE TABLE betalens.dataset_coverage (
    logical_dataset VARCHAR(32) PRIMARY KEY,
    min_available_at TIMESTAMP,
    max_available_at TIMESTAMP,
    row_count BIGINT NOT NULL DEFAULT 0 CHECK (row_count >= 0),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb
);
